### ISSUE TITLE
Light and Dark Mode

### ISSUE THREAD

**Issue by MayaGans** [gadenbuie/xaringanthemer#38]
Leaving this note for myself for a half baked idea that you could prob beat me to executing but let the user add a little button to the top right of their slides so the viewer can toggle between light and dark mode which would invert their color palettes (and _obviously_ with a cute little sun icon to toggle to light and moon for dark)

**Comment by gadenbuie** [comment]
Cool idea! Have you seen [colinfay/darkmode](https://github.com/colinfay/darkmode), that's probably a good place to start (and it doesn't work out of the box with remarkjs).

The other way to go is to take advantage of the fact that the slide theme is powered entirely by CSS variables. With this route, you can use the `prefers-color-scheme: dark` media query and change key CSS custom properties for dark slides.

```css
@media (prefers-color-scheme: dark) {
  :root {
    /* invert foreground/background colors for "dark mode" */
    --text-color: #FFFFFF;
    --background-color: #000000;
    /* ... etc ... */
  }
}
```

This happens passively based on OS settings, so it isn't as fancy as a JavaScript implementation... but it works pretty well. I guess we'd only need a helper function for appending the media query, something like `style_prefers_dark_scheme()` or `style_darkmode()`.
