### ISSUE TITLE
text_slide_number_font_size applied to "text-size" instead of "font-size"

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/xaringanthemer#5]
```r
text_slide_number_font_size = "15px"
```

gives the following in `xaringan-themer.css`

```css
.remark-slide-number {
  text-size: 15px;
}
```
