### ISSUE TITLE
Table row highlights - switch off for certain tables

### ISSUE THREAD

**Issue by dragonattheend** [gadenbuie/xaringanthemer#74]
Thanks a lot for your work!
I'm using your package, my YAML is 
```
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      # slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
```
And themer setting is 

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

I have some markdown and stargazer tables in my presentation. 

I see that every other row gets highlighted in any table. 

While I'm okay with it in some tables, I'd like to remove it for the `stargazer` regression tables. 

```{r, echo=FALSE, results='asis'}
stargazer(lm.1, lm.2, type = "html", single.row = TRUE)
```
where I want to highlight a 1 certain row and leave others unformatted.
